name: 'Stackgen CLI'

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Stackgen CLI'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Stackgen CLI
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
        source ~/.bashrc

    - name: Stackgen Provision - Plan action
      run: 'stackgen provision --appstack-id=7e3dbbf6-6d38-4766-9da6-6725d5d7a048 --var=`region=eu-west-3`'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        STACKGEN_PAT: ${{ secrets.STACKGEN_PAT }}

    - name: Stackgen Provision - Apply action
      run: 'stackgen provision --appstack-id=7e3dbbf6-6d38-4766-9da6-6725d5d7a048 --var=`region=eu-west-3` --apply'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        STACKGEN_PAT: ${{ secrets.STACKGEN_PAT }}